# Generated by Django 5.2.5 on 2025-08-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="farmeruser",
            name="farm_type",
        ),
        migrations.AddField(
            model_name="farmeruser",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="farmeruser",
            name="otp_created_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="farmeruser",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
